---
title: "tutor"
author: "ravi.prakash"
date: "2024-03-16"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
name <- c("Ravi", "Shruti", "Dummy1", "Dummy2", "Dummy3", "Dummy4", "dUMMY5")
age <- c(26, 26, 25, 40, 45, 34, 48)
is_married <- c(FALSE, FALSE, FALSE, TRUE, TRUE, TRUE, TRUE)
```

```{r}
name
```

```{r}
print(age)
```

```{r}
print(is_married)
```

```{r}
df = tibble(Name = name, Age = age, MARRIAGE = is_married) # df = data.frame(Name = ....)
```

```{r}
df
```

```{r}
name <- c("Ravi", "Shruti", "Dummy1", "Dummy2", "Dummy3", "Dummy4", "dUMMY5")
age <- c(26L, 26L, 25L, 40L, 45L, 34L, 48L)
is_married <- c(FALSE, FALSE, FALSE, TRUE, TRUE, TRUE, TRUE)

df2 = data.frame(People = name, Age = age, MARRIAGE = is_married)
```

```{r}
print(df2)
```

```{r}
df <- tibble(Person = name, Age_in_years = age, Marriage_status = is_married)
```

```{r}
df
```

```{r}
head(x = df, n = 4)   # function(argument1 = value, argument2 = value, ......)
```


```{r}
df[3, 2]
```


```{r}
df[2, ]
```


```{r}
a <- 5 # initializing a variable
b <- 4
c <- a * b
```


```{r}
```


```{r}
ages_vector <- df[,2]
```


```{r}
ages_vector
```


```{r}
class(df)
```


```{r}
class(df[,2])
```


```{r}
head(x = df, n = 3)
```


```{r}
df[, 2]
```


```{r}
df$Age_in_years
```


```{r}
vec <- c(1,10,34,56,90)
```


```{r}
indices <- c(1,3)
vec[indices]
```


```{r}
vec[c(1,3)]
```


```{r}
df
```


```{r}
row_num <- c(1,2)
col_num <- c(2,3)
df[row_num, col_num]
```


```{r}
df[c(1,2), c(2,3)]
```


```{r}
df$Age_in_years > 30
```


```{r}
df[1,]
```


```{r}
df[c(1,2), ]
```


```{r}
filtered_rows <- df$Age_in_years > 30
df[filtered_rows , ]
```





```{r}
```


```{r}
```


```{r}
```


```{r}
```
